Correct locations for SPL headers and build SPL
* spl autoconf checks
* use zfs_config.h instead of spl_config.h
* generate a Makefile for spl module
* SPL include files for modules under include/spl
* Mark SPL module as GPL (different than META_LICENSE)
* fixup to unload_modules() in zfs-common.sh
* Add spl.ko to list of ZFS modules
* Remove splat
* Include SPL in built packages
* Remove std=gnu99 for module builds

ZFS module code is gnu99 compliant.  SPL module code is not, at least
with RHEL 7.3.  Using -std=gnu99 on RHEL 7.3 produces this build
failure:

In file included from
/g/g0/faaland1/projects/zfs/module/spl/spl-kmem.c:30:0:
include/linux/ratelimit.h:22:9: error: initializer element is not
constant
  struct ratelimit_state name = {     \
         ^
/g/g0/faaland1/projects/zfs/module/spl/spl-kmem.c:139:1: note: in
expansion of macro DEFINE_RATELIMIT_STATE
 DEFINE_RATELIMIT_STATE(kmem_alloc_ratelimit_state, 60 * HZ, 5);
 ^
include/linux/ratelimit.h:22:9: error: (near initialization for
kmem_alloc_ratelimit_state.lock)
  struct ratelimit_state name = {     \
         ^
/g/g0/faaland1/projects/zfs/module/spl/spl-kmem.c:139:1: note: in
expansion of macro DEFINE_RATELIMIT_STATE
 DEFINE_RATELIMIT_STATE(kmem_alloc_ratelimit_state, 60 * HZ, 5);
 ^

* Add a script for fixing style issues, to be run
against each file e.g.

find ./include -name '*.h' | xargs -n1 scripts/fix-spl-style

Signed-off-by: Olaf Faaland <faaland1@llnl.gov>